Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/d/Library/Python/3.11/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

data = {
    "Type of ML": ["Supervised", "Unsupervised", "Semi-Supervised", "Reinforcement", "Transfer", "GANs"],
    "Pros": [
        "Direct feedback, High accuracy with enough data",
        "Works with unlabeled data, Can uncover hidden patterns",
        "Leverages large amounts of unlabeled data",
        "Adapts to dynamic environments, Potential for real-time learning",
        "Saves training time, Can leverage pre-trained models",
        "Generates new data, Can achieve impressive realism"
    ],
    "Cons": [
        "Needs labeled data, Can overfit",
        "No feedback, Harder to verify results",
        "Needs some labeled data, Combines challenges of both supervised and unsupervised",
        "Requires careful reward design, Can be computationally expensive",
        "Not always straightforward, Domain differences can be an issue",
        "Training can be unstable, May require lots of data and time"
    ]
}

df = pd.DataFrame(data)

for index, row in df.iterrows():
    print(f"Type of ML: {row['Type of ML']}\nPros: {row['Pros']}\nCons: {row['Cons']}\n{'-'*40}")

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m data [38;5;241m=[39m {
[1;32m      4[0m     [38;5;124m"[39m[38;5;124mType of ML[39m[38;5;124m"[39m: [[38;5;124m"[39m[38;5;124mSupervised[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mUnsupervised[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mSemi-Supervised[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mReinforcement[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mTransfer[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mGANs[39m[38;5;124m"[39m],
[1;32m      5[0m     [38;5;124m"[39m[38;5;124mPros[39m[38;5;124m"[39m: [
[0;32m   (...)[0m
[1;32m     20[0m     ]
[1;32m     21[0m }
[1;32m     23[0m df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(data)

[0;31mModuleNotFoundError[0m: No module named 'pandas'

