Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/d/Library/Python/3.11/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tabulate import tabulate

# Define the table data as a list of lists
data = [
    ["studentuniverse", "", "mozart", "shaKespeare", "2023-06-15"],
    ["alaskan", "340733890", "mozart", "shaKespeare", "2023-02-05"],
    ["frontier", "90102556651", "mozart", "shaKespeare", "2023-07-06"]
]

# Define the table headers
headers = ["account", "number", "username", "password", "date"]

# Generate the table
table = tabulate(data, headers, tablefmt="")

# Print the table
print(table)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtabulate[39;00m [38;5;28;01mimport[39;00m tabulate
[1;32m      3[0m [38;5;66;03m# Define the table data as a list of lists[39;00m
[1;32m      4[0m data [38;5;241m=[39m [
[1;32m      5[0m     [[38;5;124m"[39m[38;5;124mstudentuniverse[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmozart[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mshaKespeare[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m2023-06-15[39m[38;5;124m"[39m],
[1;32m      6[0m     [[38;5;124m"[39m[38;5;124malaskan[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m340733890[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmozart[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mshaKespeare[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m2023-02-05[39m[38;5;124m"[39m],
[1;32m      7[0m     [[38;5;124m"[39m[38;5;124mfrontier[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m90102556651[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmozart[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mshaKespeare[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m2023-07-06[39m[38;5;124m"[39m]
[1;32m      8[0m ]

[0;31mModuleNotFoundError[0m: No module named 'tabulate'

